version: '3'
services:
  go-api:
    container_name: go-api
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: on-failure
    networks:
      - go-api-network

volumes:
  postgres:


networks:
  go-api-network:
    name: go-api
    driver: bridge
