version: '3'
services:
  go-script:
    container_name: go-script
    build:
      context: .
      dockerfile: ./Dockerfile.local
    restart: on-failure
    networks:
      - go-script-network

networks:
  go-script-network:
    name: go-script
    driver: bridge
